name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # schedule:
  #   - cron: "*/7 * * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: AUDC

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ${{ env.CABAL_DIR }}
        key: ${{ runner.os }}-primes

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies

    - name: Build
      run: cabal build

    - name: Run
      env:
        DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: cabal run
